# Caminho para o diretório raiz do dataset. Pode ser um caminho absoluto ou relativo.
# O ponto '.' significa 'esta pasta atual', o que é uma boa prática se o yaml estiver na raiz do projeto.
path: ../dataset_passaros  # IMPORTANTE: Ajuste este caminho!

# Caminhos para as pastas de imagens de treino e validação (relativos ao 'path' acima)
train: images/train
val: images/val

# Nomes das classes, NA ORDEM CORRETA (do 0 em diante)
names:
  0: olho
  1: bico
  2: asa
  3: garra
  4: cauda
  5: corpo