# Configurações do Sistema de Identificação de Pássaros
# TCC - 2025

# Caminhos dos dados
data:
  datasets: "data/datasets"
  models: "data/models"
  cache: "data/cache"
  learning: "data/learning_data"
  manual_analysis: "data/manual_analysis"

# Configurações dos modelos
models:
  yolo:
    path: "data/models/yolov8n.pt"
    trained_path: "data/models/runs/detect/train/weights/best.pt"
    config: "config/models.yaml"
  keras:
    path: "data/models/modelo_classificacao_passaros.keras"
    input_size: [224, 224, 3]
    classes: 6

# Configurações de treinamento
training:
  yolo:
    epochs: 250
    batch_size: 16
    patience: 50
  keras:
    epochs: 100
    batch_size: 32
    validation_split: 0.2

# Configurações do sistema
system:
  debug: false
  log_level: "INFO"
  sync_interval: 30
  retrain_threshold: 5
